#!/usr/bin/env python3
import os
import time
import json
import subprocess
from datetime import datetime

REPO_ROOT = os.environ.get('REPO_ROOT', '/repo')
QUEUE_PATH = os.environ.get('QUEUE_PATH', '/repo/data/publish_queue.jsonl')
SUGGESTIONS_DIR = os.environ.get('SUGGESTIONS_DIR', '/repo/suggestions')
LOG_PATH = os.environ.get('LOG_PATH', '/repo/logs/agent-runner.log')
POLL_INTERVAL = float(os.environ.get('POLL_INTERVAL', '30'))

os.makedirs(SUGGESTIONS_DIR, exist_ok=True)

processed_offset_path = os.path.join(SUGGESTIONS_DIR, '.processed_offset')


def log(msg):
    line = f"[{datetime.utcnow().isoformat()}] {msg}\n"
    print(line, end='')
    try:
        with open(LOG_PATH, 'a', encoding='utf-8') as f:
            f.write(line)
    except Exception:
        pass


def detect_opencode():
    try:
        r = subprocess.run(['opencode', '--version'], capture_output=True, text=True, timeout=10)
        return r.returncode == 0
    except Exception:
        return False


def try_opencode_generate(prompt: str):
    # try several common opencode CLI patterns
    cmds = [
        ['opencode', 'run', '--model', 'opencode/big-pickle'],
        ['opencode', 'generate', '--model', 'opencode/big-pickle'],
        ['opencode', 'infer', '--model', 'opencode/big-pickle'],
        ['opencode', 'chat', '--model', 'opencode/big-pickle']
    ]
    last_err = ''
    for cmd in cmds:
        try:
            p = subprocess.run(['opencode','run','--prompt' , prompt, '--model','opencode/big-pickle'], capture_output=True, text=True, timeout=180, cwd=REPO_ROOT)
            if p.returncode == 0 and p.stdout.strip():
                return {'ok': True, 'cmd': ' '.join(cmd), 'output': p.stdout}
            last_err = p.stderr or p.stdout
        except Exception as e:
            last_err = str(e)
    return {'ok': False, 'error': last_err}


def read_new_envelopes():
    if not os.path.exists(QUEUE_PATH):
        return []
    offset = 0
    if os.path.exists(processed_offset_path):
        try:
            with open(processed_offset_path, 'r') as f:
                offset = int(f.read().strip() or 0)
        except Exception:
            offset = 0
    envelopes = []
    try:
        with open(QUEUE_PATH, 'r', encoding='utf-8') as f:
            for i, line in enumerate(f):
                if i < offset:
                    continue
                line = line.strip()
                if not line:
                    continue
                try:
                    envelopes.append(json.loads(line))
                except Exception:
                    envelopes.append({'raw': line})
        new_offset = offset + len(envelopes)
        with open(processed_offset_path, 'w') as f:
            f.write(str(new_offset))
    except Exception as e:
        log(f"Failed reading queue: {e}")
    return envelopes


def make_suggestion(envelope, idx, opencode_available):
    ts = datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')
    fname = os.path.join(SUGGESTIONS_DIR, f'suggestion_{ts}_{idx}.json')
    suggestion = {
        'timestamp': datetime.utcnow().isoformat(),
        'envelope': envelope,
        'opencode_available': opencode_available,
        'notes': []
    }
    prompt = ''
    try:
        plan_path = os.path.join(REPO_ROOT, 'PLAN.md')
        plan_snippet = ''
        if os.path.exists(plan_path):
            with open(plan_path, 'r', encoding='utf-8') as pf:
                plan_snippet = pf.read(2000)
        prompt = f"Repo PLAN.md excerpt:\n{plan_snippet}\n\nEnvelope:\n{json.dumps(envelope, ensure_ascii=False, indent=2)}\n\nTask: Propose one concrete code change or new file to progress the PlebX project (MVP). Output JSON with keys: title, description, files (array of {path, patch}), rationale."
    except Exception:
        prompt = 'Generate a suggested code change for PlebX based on available plan and envelope.'

    if not opencode_available:
        suggestion['notes'].append('opencode CLI not available on PATH. To enable AI-generated patches, install opencode CLI inside the agent-runner container or on host.')
        suggestion['suggested_prompt'] = prompt
        # write suggestion file
        try:
            with open(fname, 'w', encoding='utf-8') as f:
                json.dump(suggestion, f, indent=2)
            log(f"Wrote suggestion (no-opencode) -> {fname}")
        except Exception as e:
            log(f"Failed writing suggestion: {e}")
        return

    # opencode available: attempt generation
    res = try_opencode_generate(prompt)
    if res.get('ok'):
        suggestion['ai_cmd'] = res.get('cmd')
        suggestion['ai_output'] = res.get('output')
        suggestion['notes'].append('Generated by opencode CLI')
    else:
        suggestion['notes'].append('opencode invocation failed')
        suggestion['ai_error'] = res.get('error')
        suggestion['suggested_prompt'] = prompt

    try:
        with open(fname, 'w', encoding='utf-8') as f:
            json.dump(suggestion, f, indent=2)
        log(f"Wrote suggestion -> {fname}")
    except Exception as e:
        log(f"Failed writing suggestion: {e}")


if __name__ == '__main__':
    log('agent-runner starting')
    opencode_avail = detect_opencode()
    log(f'opencode available: {opencode_avail}')
    idx = 0
    while True:
        try:
            envelopes = read_new_envelopes()
            if envelopes:
                log(f'Found {len(envelopes)} new envelope(s)')
            for env in envelopes:
                make_suggestion(env, idx, opencode_avail)
                idx += 1
        except Exception as e:
            log(f'Loop error: {e}')
        time.sleep(POLL_INTERVAL)
